/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author User
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuAdmin = new javax.swing.JMenuItem();
        jMenuPaket = new javax.swing.JMenuItem();
        jMenuPengunjung = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemPemesanan = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuLaporanAdmin = new javax.swing.JMenuItem();
        jMenuLaporanPengunjung = new javax.swing.JMenuItem();
        jMenuLaporanPemesanan = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/susur sungai.png"))); // NOI18N

        jMenu1.setText("MASTER DATA");

        jMenuAdmin.setText("Data Admin");
        jMenuAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAdminActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuAdmin);

        jMenuPaket.setText("Data Paket Wisata");
        jMenuPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPaketActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuPaket);

        jMenuPengunjung.setText("Data Pengunjung");
        jMenuPengunjung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPengunjungActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuPengunjung);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("TRANSAKSI");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItemPemesanan.setText("Pemesanan");
        jMenuItemPemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPemesananActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemPemesanan);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("LAPORAN");

        jMenuLaporanAdmin.setText("Laporan Data Admin");
        jMenuLaporanAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLaporanAdminActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuLaporanAdmin);

        jMenuLaporanPengunjung.setText("Laporan Paket Wisata");
        jMenuLaporanPengunjung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLaporanPengunjungActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuLaporanPengunjung);

        jMenuLaporanPemesanan.setText("Laporan Pemesanan");
        jMenuLaporanPemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLaporanPemesananActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuLaporanPemesanan);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAdminActionPerformed
        try {
            new dataAdmin().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuAdminActionPerformed

    private void jMenuPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPaketActionPerformed
        try {
            new dataPaketWisata().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuPaketActionPerformed

    private void jMenuPengunjungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPengunjungActionPerformed
        try {
            new dataPengunjung().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuPengunjungActionPerformed

    private void jMenuLaporanAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLaporanAdminActionPerformed
        try {
            new laporanAdmin().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuLaporanAdminActionPerformed

    private void jMenuItemPemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPemesananActionPerformed
        new dataPemesanan().setVisible(true);
    }//GEN-LAST:event_jMenuItemPemesananActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuLaporanPengunjungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLaporanPengunjungActionPerformed
        try {
            new laporanPaketWisata().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuLaporanPengunjungActionPerformed

    private void jMenuLaporanPemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLaporanPemesananActionPerformed
        try {
            new laporanPemesanan().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuLaporanPemesananActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuAdmin;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemPemesanan;
    private javax.swing.JMenuItem jMenuLaporanAdmin;
    private javax.swing.JMenuItem jMenuLaporanPemesanan;
    private javax.swing.JMenuItem jMenuLaporanPengunjung;
    private javax.swing.JMenuItem jMenuPaket;
    private javax.swing.JMenuItem jMenuPengunjung;
    // End of variables declaration//GEN-END:variables
}
